# udfilt
#
# Filt out undesired psiFinder information by six key identification thresholds

#' Filt out undesired psiFinder information by six key identification thresholds
#' @param RpsiFinder_res_file The psiFinder result file generated by RpsiFinder function
#' @param treatPreRpmFold_thres The filtering threshold for treatPreRpmFold
#' @param treatAfterRpmFold_thres The filtering threshold for treatAfterRpmFold
#' @param treatStopRatio_thres The filtering threshold for treatStopRatio
#' @param preRpmFoldRatio_thres The filtering threshold for preRpmFoldRatio
#' @param afterRpmFoldRatio_thres The filtering threshold for afterRpmFoldRatio
#' @param stopRatioFC_thres The filtering threshold for stopRatioFC
#' @param output_dir The path to the output directory
#' @param output_name The path to the output file
#' @export
#'
udfilt <- function(RpsiFinder_res_file,
                   treatPreRpmFold_thres,
                   treatAfterRpmFold_thres,
                   treatStopRatio_thres,
                   preRpmFoldRatio_thres,
                   afterRpmFoldRatio_thres,
                   stopRatioFC_thres,
                   output_dir,
                   output_name)
{
  RpsiFinder_res_file<-fread(RpsiFinder_res_file)
  udfilt_res<-RpsiFinder_res_file %>% mutate(class = if_else(treatPreRpmFold>treatPreRpmFold_thres &
                                                               treatAfterRpmFold>treatAfterRpmFold_thres &
                                                               treatStopRatio>treatStopRatio_thres &
                                                               preRpmFoldRatio>preRpmFoldRatio_thres &
                                                               afterRpmFoldRatio>afterRpmFoldRatio_thres &
                                                               stopRatioFC>stopRatioFC_thres, 1, 0))
  output_dir_output_name<-paste(output_dir,"/",output_name,sep="")
  fwrite(x=udfilt_res,file=paste(output_dir_output_name,".txt",sep=""),sep="\t")
  write.table(udfilt_res,paste(output_dir_output_name,".bed",sep=""),row.names=F,col.names=F,quote=F,sep="\t")
  return(udfilt_res)
}
